/* ============================================================================
* filename.h
* ============================================================================
* @file    app_main.h
* @author  Hugo Juarez
* @date    2026-02-26
* @version 0.1.0
*
* @brief   This is the application layer entry point of the app.
*
* @details
* App main allows the separation of written code without the need of modifying main.h and main.c
* which are autogenerated by STM32CubeMX this allows for a more natural separation of the code
* and imporves readability.
*
* @note
* app_init() and app_start() are called in main.c to initiliaze the application
*
* @copyright Copyright (c) 2026 Hugo Juarez. Licensed under the MIT License.
*             See LICENSE file in the root of the repository for details.
*/

#ifndef FLIGHT_CONTROLLER_APP_MAIN_H
#define FLIGHT_CONTROLLER_APP_MAIN_H

#include "fc_types.h"

/* =========================================================================
* Public Function Prototypes
* ========================================================================= */
FC_Status_t app_init(void);
FC_Status_t app_start(void);

#endif //FLIGHT_CONTROLLER_APP_MAIN_H