/* ============================================================================
* pin_map.h
* ============================================================================
*
* @file    pin_map.h
* @author  Hugo Juarez
* @date    2026-02-26
* @version 0.1.0
*
* @brief   Pin out layout definition.
*
* @details
* PIN OUT definition. This file is dependant of autogenerated files from
* STM32CubeMX
*
* @copyright Copyright (c) 2026 Hugo Juarez. Licensed under the MIT License.
*             See LICENSE file in the root of the repository for details.
* ========================================================================= */
#ifndef FLIGHT_CONTROLLER_PIN_MAP_H
#define FLIGHT_CONTROLLER_PIN_MAP_H

#include "stm32f7xx_hal.h"

/* =========================================================================
* Defines
* ========================================================================= */

#define LED_PIN             GPIO_PIN_0
#define LED_GPIO_Port       GPIOB

#endif //FLIGHT_CONTROLLER_PIN_MAP_H